---
- name: Install package
  pacman:
    name: postgresql
    update_cache: yes
  become: yes

- name: Initialize database
  command: /usr/bin/initdb -D '/var/lib/postgres/data'
  args:
    creates: /var/lib/postgres/data
  become: yes
  become_user: postgres

- name: Enable and start service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes
