---
- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - postgresql
    - python-psycopg2
  become: yes

- name: Create user
  postgresql_user:
    name: "{{ postgresql_user }}"
    role_attr_flags: "{{ postgresql_roles | join(',') }}"
  become: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ postgresql_db }}"
    owner: "{{ postgresql_user }}"
  become: yes
  become_user: postgres
