---
- name: Install package
  pacman:
    name: postgresql
    update_cache: yes
  become: yes

- name: Initialize database
  command: "/usr/bin/initdb -D {{ postgresql_data_dir }}"
  args:
    creates: "{{ postgresql_data_dir }}"
  become: yes
  become_user: postgres

- name: Enable and start service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes
