---
- name: Add repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  become: yes

- name: Add repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: pgdg
  become: yes

- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql-10
    - python-psycopg2
  become: yes

- name: Add user
  postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: Add database
  postgresql_db:
    name: "{{ ansible_user_id }}"
  become: yes
  become_user: postgres
