---
- name: Add repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  become: yes

- name: Add repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
  become: yes

- name: Install package
  apt:
    name: postgresql-10
    update_cache: yes
  become: yes
