---
- name: Add repository key
  apt_key:
    url: "{{ postgresql_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ postgresql_repo }}"
    filename: pgdg
    state: present
  become: true

- name: Install packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  become: true
