---
- name: Add repository key
  apt_key:
    url: "{{ postgresql_repo_key }}"
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ postgresql_repo }}"
    filename: postgresql
  become: true

- name: Install packages
  apt:
    name: "{{ postgresql_packages }}"
    update_cache: true
  become: true

- name: Add user
  postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER
  become: true
  become_user: postgres

- name: Add database
  postgresql_db:
    name: "{{ ansible_user_id }}"
  become: true
  become_user: postgres
