---
- name: Add repository key
  apt_key:
    url: "{{ dotnet_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ dotnet_repo }}"
    filename: microsoft-prod
  become: true

- name: Install packages
  apt:
    name: "{{ dotnet_packages }}"
    state: present
    update_cache: true
  become: true
