---
- name: Install dependencies
  apt:
    name: git
    update_cache: yes
  become: yes

- name: Clone repository
  git:
    repo: "{{ antigen_repo }}"
    dest: "{{ antigen_dest }}"
    version: "{{ antigen_version }}"

- name: Copy zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
