---
- name: Clone repository
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish.git
    dest: "{{ omf_dir }}"

- name: Clone plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ omf_dir }}/pkg/{{ item.name }}"
  with_items: "{{ omf_plugins }}"
