---
- name: Install packages
  community.general.homebrew:
    name:
      - fish
      - fisher
      - fzf
  tags: homebrew

- name: Add shell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
  become: true

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  become: true

- name: Install fisher plugins
  ansible.builtin.shell:
    cmd: "fisher install {{ item.name }}"
    executable: /usr/local/bin/fish
    creates: "{{ item.creates }}"
  loop:
    - { name: PatrickF1/fzf.fish, creates: ~/.config/fish/conf.d/fzf.fish }
