---
- name: Install fish
  community.general.homebrew:
    name: fish

- name: Add fish to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    regexp: "^\/usr\/local\/bin\/fish$"
    line: /usr/local/bin/fish
  become: true

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  become: true
