---
- name: Install package
  apt:
    name: fish
    state: present
  become: true

- name: Change user shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
    state: present
  become: true

- import_role:
    name: config-files
  vars:
    config_files: "{{ fish_completions_files }}"
    config_files_dir: "{{ fish_completions_dir }}"
    config_files_extension: fish
  tags: dotfiles

- import_role:
    name: config-files
  vars:
    config_files: "{{ fish_confd_files }}"
    config_files_dir: "{{ fish_confd_dir }}"
    config_files_extension: fish
  tags: dotfiles

- name: conf.d - Create directory
  file:
    path: "{{ fish_confd_dir }}"
    state: directory

- name: conf.d - Copy files
  copy:
    dest: "{{ fish_confd_dir }}/{{ item.key }}.fish"
    content: "{{ item.value }}"
  with_dict: "{{ fish_confd_files }}"
