---
- name: Install packages
  community.general.homebrew:
    name:
      - fish
      - fisher

- name: Add shell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
  become: true

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  become: true
