---
- name: Install package
  apt:
    name: fish
    state: present
  become: true

- name: Change user shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
    state: present
  become: true

- import_tasks: completions.yml
  tags: dotfiles

- import_tasks: confd.yml
  tags: dotfiles
