---
- name: Install package
  apt:
    name: fish
    state: present
  become: yes

- name: Change shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/fish/completions
    - ~/.config/fish/conf.d
