---
- apt:
    name: fish
    state: present
  become: yes

- user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
    state: present
  become: yes

- name: Create configuration directory
  file:
    path: ~/.config/fish/conf.d
    state: directory
