---
- name: Install packages
  community.general.homebrew:
    name:
      - fish
      - fisher
      - fzf
  tags: homebrew

- name: Add shell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
  become: true

- name: Install fzf plugin
  ansible.builtin.shell:
    cmd: fisher install PatrickF1/fzf.fish
    executable: /usr/local/bin/fish

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/fish/conf.d
    state: directory
    mode: '0744'
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.file:
    src: "{{ role_path }}/files/greeting.fish"
    dest: ~/.config/fish/conf.d/greeting.fish
    state: link
    force: true
  tags: dotfiles
