---
- name: Add repository key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present

- name: Add repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/4.2 main"
    filename: mongodb
    state: present

- name: Install packages
  apt:
    name: mongodb-org
    update_cache: true
    state: present
