---
virtualbox_repo_keys:
  - https://www.virtualbox.org/download/oracle_vbox_2016.asc
  - https://www.virtualbox.org/download/oracle_vbox.asc

virtualbox_repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

virtualbox_packages:
  - virtualbox-6.0
