---
- include_role:
    name: version_manager
  vars:
    version_manager_name: nvm
    version_manager_repo: "{{ nvm_repo }}"
    version_manager_dest: "{{ nvm_dest }}"
    version_manager_version: "{{ nvm_version }}"
