---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ nvm_deps }}"
  become: yes

- name: Clone repository
  git:
    repo: "{{ nvm_repo }}"
    dest: "{{ nvm_dest }}"
    version: "{{ nvm_version }}"

- name: Install versions
  shell: |
    . {{ nvm_dest }}/nvm.sh
    nvm install {{ item }}
  args:
    creates: "{{ nvm_dest }}/versions/node/{{ item }}"
  with_items: "{{ nvm_versions }}"
