---
- name: Clone repository
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_dir }}"
    version: v0.33.11

- include_tasks: version.yml
  with_items: "{{ nvm_versions }}"
  loop_control:
    loop_var: version
