---
- name: Clone nvm
  git:
    repo: "{{ nvm_repo }}"
    version: "{{ nvm_version }}"
    dest: "{{ nvm_dest }}"

- name: Create systemd user directory
  file:
    path: "{{ systemd_user_dir }}"
    state: directory

- name: Copy nvm updater timer
  copy:
    src: nvm-updater.timer
    dest: "{{ systemd_user_dir }}/nvm-updater.timer"

- name: Copy nvm updater service
  template:
    src: nvm-updater.service.j2
    dest: "{{ systemd_user_dir }}/nvm-updater.service"

- name: Enable nvm updater timer
  systemd:
    name: nvm-updater.timer
    state: started
    enabled: yes
    daemon_reload: yes
    user: yes
