---
- name: Add repository key
  apt_key:
    url: "{{ google_chrome_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ google_chrome_repo }}"
    state: present
    filename: google-chrome
  become: true

- name: Install package
  apt:
    name: "{{ google_chrome_package }}"
    state: present
    update_cache: true
  become: true
