---
- name: Add repository key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: true

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
  become: true

- name: Install package
  apt:
    name: google-chrome-stable
    update_cache: true
  become: true
