---
- hosts: localhost
  roles:
    - { role: asdf, tags: asdf }
    - { role: direnv }
    - { role: fish }
    - { role: fzf }
    - { role: git }
    - { role: homebrew, tags: homebrew }
    - { role: neovim }
    - { role: starship }
    - { role: tmux }
