---
- import_playbook: playbooks/applications.yml
- import_playbook: playbooks/databases.yml
- import_playbook: playbooks/editors.yml
- import_playbook: playbooks/managers.yml
- import_playbook: playbooks/shell.yml
- import_playbook: playbooks/system.yml
- import_playbook: playbooks/virtualization.yml
