---
- import_playbook: playbooks/applications.yml
  tags: applications
#- import_playbook: playbooks/databases.yml
  #tags: databases
- import_playbook: playbooks/editors.yml
  tags: editors
- import_playbook: playbooks/managers.yml
  tags: databases
- import_playbook: playbooks/shell.yml
  tags: shell
- import_playbook: playbooks/system.yml
  tags: system
- import_playbook: playbooks/virtualization.yml
  tags: virtualization
