---
- name: Generate source.list
  template:
    src: source.list.j2
    dest: /etc/apt/sources.list
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install packages
  apt:
    name: "{{ apt_packages }}"
    state: present
  become: yes
