---
- name: Create directory
  file:
    path: "{{ tpm_dir }}"
    state: directory

- name: Clone repository
  git:
    repo: "{{ tpm_repo }}"
    dest: "{{ tpm_dir }}"
    version: "{{ tpm_version }}"
