---
version_managers_nvm_repo: https://github.com/creationix/nvm.git
version_managers_nvm_dest: "{{ ansible_user_dir }}/.nvm"
version_managers_nvm_version: v0.33.11

version_managers_pyenv_repo: https://github.com/pyenv/pyenv.git
version_managers_pyenv_dest: "{{ ansible_user_dir }}/.pyenv"
version_managers_pyenv_version: v1.2.4

version_managers_rbenv_repo: https://github.com/rbenv/rbenv.git
version_managers_rbenv_dest: "{{ ansible_user_dir }}/.rbenv"
version_managers_rbenv_version: v1.1.1

version_managers_rbenv_plugins:
  ruby-build:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ version_managers_rbenv_dest }}/plugins/ruby-build"
    version: v20180618
