---
- name: Add repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
  become: yes

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
  become: yes

- name: Install package
  apt:
    name: code
    update_cache: yes
  become: yes
