---
- name: Create directory
  file:
    path: "{{ vim_plug_dir }}"
    state: directory

- name: Download file
  get_url:
    url: "https://github.com/junegunn/vim-plug/releases/download/{{ vim_plug_version }}/plug.vim"
    dest: "{{ vim_plug_dir }}/plug.vim"
