---
- name: Install package
  apt:
    name: direnv
    state: present
  become: true
  when: not direnv_asdf_enabled

- name: Create config directory
  file:
    path: ~/.config/direnv
    state: directory

- name: Create config file
  template:
    src: direnvrc.j2
    dest: ~/.config/direnv/direnvrc
