---
# Manual steps:
# - asdf plugin add direnv
# - asdf install direnv latest
# - asdf global direnv latest

- name: Install direnv
  community.general.homebrew:
    name: direnv

- name: Symlink direnvrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/direnvrc"
    dest: ~/.config/direnv/direnvrc
    state: link
  tags: dotfiles

- name: Symlink direnv.fish
  ansible.builtin.file:
    src: "{{ role_path }}/files/direnv.fish"
    dest: ~/.config/fish/conf.d/direnv.fish
    state: link
  tags: dotfiles
