---
# Manual steps:
# - asdf plugin add direnv
# - asdf install direnv latest
# - asdf global direnv latest

- name: Install package
  community.general.homebrew:
    name: direnv
  tags: homebrew

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/direnv
    state: directory
  tags: dotfiles

- name: Create config file
  ansible.builtin.copy:
    src: direnvrc
    dest: ~/.config/direnv/direnvrc
  tags: dotfiles

- name: Check fish directory
  ansible.builtin.stat:
    path: ~/.config/fish/conf.d
  register: fish_conf_dir
  tags:
    - dotfiles
    - fish

- name: Copy fish config
  ansible.builtin.copy:
    src: direnv.fish
    dest: ~/.config/fish/conf.d/direnv.fish
  when:
    - ansible_user_shell == "/usr/local/bin/fish"
    - fish_conf_dir.stat.exists
  tags:
    - dotfiles
    - fish
