---
# Manual steps:
# - asdf plugin add direnv
# - asdf install direnv latest
# - asdf global direnv latest

- name: Install package
  community.general.homebrew:
    name: direnv
  tags: homebrew

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/direnv
    state: directory
    mode: '0744'
  tags: dotfiles

- name: Create config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/direnvrc"
    dest: ~/.config/direnv/direnvrc
    state: link
    force: true
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.file:
    src: "{{ role_path }}/files/direnv.fish"
    dest: ~/.config/fish/conf.d/direnv.fish
    state: link
    force: true
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish
