---
# Manual steps:
# - asdf plugin add direnv
# - asdf install direnv latest
# - asdf global direnv latest

- name: Install package
  community.general.homebrew:
    name: direnv

- name: Create configuration
  ansible.builtin.copy:
    src: direnvrc
    dest: ~/.config/direnv/direnvrc
  tags: dotfiles

- name: Create fish configuration
  ansible.builtin.file:
    src: direnv.fish
    dest: ~/.config/fish/conf.d/direnv.fish
  tags: dotfiles
