---
- import_tasks: version_manager.yml
  vars:
    name: nvm
    version_manager: "{{ version_managers.nvm }}"

- import_tasks: version_manager.yml
  vars:
    name: pyenv
    version_manager: "{{ version_managers.pyenv }}"

- import_tasks: version_manager.yml
  vars:
    name: rbenv
    version_manager: "{{ version_managers.rbenv }}"
