---
- name: Clone version manager
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    version: "{{ item.value.version }}"
  with_dict: "{{ version_managers }}"

- name: Create systemd user directory
  file:
    path: "{{ systemd_user_dir }}"
    state: directory

- name: Copy updater timer
  template:
    src: updater.timer.j2
    dest: "{{ systemd_user_dir }}/{{ item }}-updater.timer"
  with_items: "{{ version_managers.keys() }}"

- name: Copy updater service
  template:
    src: updater.service.j2
    dest: "{{ systemd_user_dir }}/{{ item.key }}-updater.service"
  with_dict: "{{ version_managers }}"

- name: Enable updater timer
  systemd:
    name: "{{ item }}-updater.timer"
    state: started
    enabled: yes
    daemon_reload: yes
    user: yes
  with_items: "{{ version_managers.keys() }}"
