---
- name: "Clone {{ name }}"
  git:
    repo: "{{ version_manager.repo }}"
    dest: "{{ version_manager.dest }}"
    version: "{{ version_manager.version }}"

- name: "Clone {{ name }} plugins"
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    version: "{{ item.value.version }}"
  with_dict: "{{ version_manager.plugins }}"
  when: version_manager.plugins is defined

- name: Create systemd user directory
  file:
    path: "{{ systemd_user_dir }}"
    state: directory

- name: "Copy {{ name }} updater timer"
  template:
    src: updater.timer.j2
    dest: "{{ systemd_user_dir }}/{{ name }}-updater.timer"

- name: "Copy {{ name }} updater service"
  template:
    src: updater.service.j2
    dest: "{{ systemd_user_dir }}/{{ name }}-updater.service"

- name: "Enable {{ name }} updater timer"
  systemd:
    name: "{{ name }}-updater.timer"
    state: started
    enabled: yes
    daemon_reload: yes
    user: yes
