---
- name: "{{ item.key }} - Configure visible-name"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/visible-name"
    value: "'{{ item.value.name }}'"
    state: present

- name: "{{ item.key }} - Configure audible-bell"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/audible-bell"
    value: "{{ item.value.audible_bell | string | lower }}"
    state: present
  when: item.value.audible_bell is defined

- name: "{{ item.key }} - Configure use-theme-colors"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/use-theme-colors"
    value: "{{ item.value.use_theme_colors | string | lower }}"
    state: present
  when: item.value.use_theme_colors is defined

- name: "{{ item.key }} - Configure background-color"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/background-color"
    value: "{{ gnome_terminal_colors[item.value.color].background_color }}"
    state: present
  when: item.value.color is defined

- name: "{{ item.key }} - Configure foreground-color"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/foreground-color"
    value: "{{ gnome_terminal_colors[item.value.color].foreground_color }}"
    state: present
  when: item.value.color is defined

- name: "{{ item.key }} - Configure palette"
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ item.key }}/palette"
    value: "{{ gnome_terminal_palettes[item.value.palette] }}"
    state: present
  when: item.value.palette is defined
