---
asdf_plugins:
  - name: nodejs
    versions:
      - number: 8.12.0
        packages:
          - neovim

  - name: python
    dependencies:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev
    versions:
      - number: 2.7.15
        packages:
          - neovim
          - pipenv

      - number: 3.7.0
        packages:
          - neovim
          - pipenv

  - name: ruby
    dependencies:
      - autoconf
      - bison
      - build-essential
      - libffi-dev
      - libgdbm-dev
      - libgdbm5
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
    versions:
      - number: 2.5.1
        packages:
          - neovim
