---
asdf_version: v0.8.0
asdf_updater: true

asdf_dir: "{{ ansible_user_dir }}/.asdf"

asdf_plugins:
  - name: nodejs
  - name: python
    versions: [2.7.18, 3.9.0]
    global: 3.9.0
    default_packages: [pynvim]
  - name: ruby
    versions: [2.6.5]
    global: 2.6.5
  - name: stack
    versions: [2.5.1]
    global: 2.5.1
