---
asdf_plugins:
  - name: nodejs
  - name: python
    dependencies:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev
    versions:
      - 2.7.16
      - 3.7.2

  - name: ruby
    dependencies:
      - autoconf
      - bison
      - build-essential
      - libffi-dev
      - libgdbm-dev
      - libgdbm5
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
    versions:
      - 2.6.1

  - name: rust
