---
asdf_updater: true

asdf_plugins:
  - name: nodejs
    versions: ["12.13.0"]
    global: "12.13.0"
  - name: python
    versions: ["2.7.17", "3.8.1"]
    global: "3.8.1"
  - name: ruby
    versions: ["2.6.5"]
    global: "2.6.5"
  - name: stack
    repo: https://github.com/sestrella/asdf-stack.git
    versions: "2.1.3"
    global: "2.1.3"

asdf_fish_abbrs:
  ai: "asdf install"
  al: "asdf list"
  ala: "asdf list-all"
