---
asdf_version: v0.8.0
asdf_updater: true

asdf_plugins:
  - name: nodejs
  - name: python
    versions: [3.8.3]
    global: 3.8.3
  - name: ruby
    versions: [2.6.5]
    global: 2.6.5
  - name: stack
    versions: [2.5.1]
    global: 2.5.1
