---
asdf_version: v0.8.0
asdf_direnv_enabled: true

asdf_plugins:
  - name: direnv
    versions: [2.27.0]
    global: 2.27.0

  - name: nodejs
    dependencies:
      - curl
      - dirmngr
      - gawk
      - gpg

  - name: python
    dependencies:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - make
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

  - name: ruby
  - name: stack
