---
fish_completions_files:
  asdf: |
    source ~/.asdf/completions/asdf.fish

fish_confd_files:
  asdf: |
    source ~/.asdf/asdf.fish

  bundle: |
    abbr be bundle exec
    abbr ber bundle exec rails
    abbr bes bundle exec rspec

  editor: |
    set -gx EDITOR vim

  fish: |
    set fish_greeting

  ghc:
    set -gx PATH /opt/ghc/bin $PATH

  git: |
    abbr ga git add
    abbr gaa git add --all
    abbr gbr git branch --remote
    abbr gc git commit -v
    abbr gc! git commit -v --amend
    abbr gco git checkout
    abbr gd git diff
    abbr gl git pull
    abbr gp git push
    abbr gst git status

  pipenv: |
    set -gx PIPENV_VENV_IN_PROJECT yes

  starship: |
    ~/.local/bin/starship init fish | source

  tmux: |
    abbr ta tmux attach -t
    abbr tkss tmux kill-session -t
    abbr tksv tmux kill-server
    abbr tl tmux list-sessions
    abbr ts tmux new-session -s
