---
tmux_plugins:
  - tmux-plugins/tmux-pain-control
  - tmux-plugins/tmux-resurrect
  - tmux-plugins/tmux-sensible
  - tmux-plugins/tmux-yank
  - tmux-plugins/tpm

tmux_conf_before_plugins: |
  set-option -g prefix C-a

  set -g base-index 1
  setw -g pane-base-index 1

  set-window-option -g mode-keys vi

  bind-key & kill-window
  bind-key x kill-pane
