---
tmux_packages:
  - fonts-powerline
  - tmux

tmux_prefix: C-a
tmux_base_index: 1
tmux_mode_keys: vi
tmux_confirmation_prompt_enabled: false

tmux_plugins:
  - jimeh/tmux-themepack
  - tmux-plugins/tmux-pain-control
  - tmux-plugins/tmux-resurrect
  - tmux-plugins/tmux-sensible
  - tmux-plugins/tpm

tmux_extra_config: |
  set -g @themepack 'powerline/double/cyan'

tmux_fish_abbrs:
  ta: tmux attach -t
  tkss: tmux kill-session -t
  tksv: tmux kill-server
  tl: tmux list-sessions
  ts: tmux new-session -s
