---
vim_has_nvim: true

vim_plugins:
  - aliou/bats.vim
  - altercation/vim-colors-solarized
  - ap/vim-css-color
  - bronson/vim-trailing-whitespace
  - ctrlpvim/ctrlp.vim
  - leafgarland/typescript-vim
  - pbrisbin/vim-syntax-shakespeare
  - peitalin/vim-jsx-typescript
  - preservim/nerdcommenter
  - preservim/nerdtree
  - tpope/vim-projectionist
  - tpope/vim-rails
  - tpope/vim-sensible
  - tpope/vim-surround
  - vim-airline/vim-airline

vim_config_after_plugins: |
  set colorcolumn=80
  set number

  set expandtab
  set shiftwidth=2
  set softtabstop=2
  set tabstop=2

  set splitbelow
  set splitright

  let mapleader = "\<Space>"
  let maplocalleader = ','

  set nobackup
  set noswapfile
  set noundofile

  set hlsearch

vim_plugin_files:
  airline: |
    let g:airline_powerline_fonts = 1

  ctrlp: |
    if executable('rg')
      set grepprg=rg\ --color=never
      let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
      let g:ctrlp_use_caching = 0
    endif

  nerdtree: |
    let g:NERDTreeShowHidden = 1

    noremap <C-n> :NERDTreeToggle<CR>

  solarized: |
    syntax enable
    set background=dark
    colorscheme solarized
