---
asdf_python_dependencies:
  - build-essential
  - curl
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev

asdf_ruby_dependencies:
  - autoconf
  - bison
  - build-essential
  - libffi-dev
  - libgdbm-dev
  - libncurses5-dev
  - libreadline6-dev
  - libssl-dev
  - libyaml-dev
  - zlib1g-dev
