---
- name: Install dependencies
  apt:
    name: curl
    state: present
  become: yes

- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- name: Copy initializer
  template:
    src: asdf.fish.j2
    dest: ~/.config/fish/conf.d/asdf.fish
  when: ansible_user_shell == "/usr/bin/fish"
  tags: dotfiles

- name: Copy configuration file
  template:
    src: asdfrc.j2
    dest: ~/.asdfrc
  tags: dotfiles
