---
- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- include_tasks: plugin.yml
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: plugin

- name: Create directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Copy updater timer
  copy:
    src: asdf-updater.timer
    dest: ~/.config/systemd/user/asdf-updater.timer

- name: Copy updater service
  template:
    src: asdf-updater.service.j2
    dest: ~/.config/systemd/user/asdf-updater.service

- name: Enable updater timer
  systemd:
    name: asdf-updater.timer
    state: started
    enabled: true
    user: true
    daemon_reload: true
