---
- name: Install package
  community.general.homebrew:
    name: asdf
  tags: homebrew

- name: Install plugins
  ansible.builtin.command:
    cmd: "asdf plugin add {{ item.name }} {{ item.url | default('') }}"
    creates: "~/.asdf/plugins/{{ item.name }}"
  loop:
    - { name: cabal, url: https://github.com/sestrella/asdf-ghcup }
    - { name: direnv }
    - { name: ghc, url: https://github.com/sestrella/asdf-ghcup }
    - { name: nodejs }
    - { name: python }
    - { name: ruby }
    - { name: rust }
