---
- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- name: Copy init script
  template:
    src: asdf.fish.j2
    dest: ~/.config/fish/conf.d/asdf.fish

- name: Install plugins
  command: "asdf plugin-add {{ item }}"
  args:
    creates: "{{ asdf_dir }}/plugins/{{ item }}"
  with_items: "{{ asdf_plugins }}"
