---
- name: Clone repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.5.1

- name: Copy scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: "{{ item.remote_src }}"
  with_items:
    - src: asdf.fish
      dest: ~/.config/fish/conf.d/asdf.fish
      remote_src: no
    - src: ~/.asdf/completions/asdf.fish
      dest: ~/.config/fish/completions/asdf.fish
      remote_src: yes

- name: Install plugins
  command: "asdf plugin-add {{ item }}"
  args:
    creates: "~/.asdf/plugins/{{ item }}"
  with_items:
    - nodejs
    - python
    - ruby
