---
- name: Install package
  community.general.homebrew:
    name: asdf
  tags: homebrew

- name: Install plugins
  ansible.builtin.command:
    cmd: "asdf plugin add {{ item }}"
    creates: "~/.asdf/plugins/{{ item }}"
  loop:
    - direnv
    - nodejs
    - python
    - ruby
    - rust
    - terraform

- name: Copy fish config
  ansible.builtin.copy:
    src: asdf.fish
    dest: ~/.config/fish/conf.d/asdf.fish
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish
