---
- name: Install dependencies
  apt:
    name: curl
    state: present
  become: yes

- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- include_tasks: plugin.yml
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: plugin
  when: asdf_plugins is defined

- import_tasks: updater.yml
  when: asdf_updater
