---
- import_tasks: install.yml

- include_tasks: plugin.yml
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: plugin
  when: asdf_plugins is defined

- import_tasks: updater.yml
  when: asdf_updater
