---
- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- name: Install plugins
  command: "asdf plugin-add {{ item.name }} {{ item.repo }}"
  args:
    creates: "~/.asdf/plugins/{{ item.name }}"
  with_items: "{{ asdf_plugins }}"

- name: Install versions
  command: "asdf install {{ item.0.name }} {{ item.1 }}"
  args:
    creates: "~/.asdf/installs/{{ item.0.name }}/{{ item.1 }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
