---
- name: Install package
  community.general.homebrew:
    name: asdf

- name: Create fish configuration
  ansible.builtin.copy:
    src: asdf.fish
    dest: ~/.config/fish/conf.d/asdf.fish
  tags: dotfiles

- name: Install plugins
  ansible.builtin.command:
    cmd: "asdf plugin add {{ item }}"
    creates: "~/.asdf/plugins/{{ item }}"
  loop:
    - direnv
    - nodejs
    - python
    - ruby
    - rust
    - terraform
