---
- name: Create ~/.config/systemd/user directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Copy asdf-updater.service
  template:
    src: asdf-updater.service.j2
    dest: ~/.config/systemd/user/asdf-updater.service
  notify: daemon_reload

- name: Copy asdf-updater.timer
  copy:
    src: asdf-updater.timer
    dest: ~/.config/systemd/user/asdf-updater.timer
  notify:
    - daemon_reload
    - reload_timer

- name: Start asdf-updater.timer
  systemd:
    name: asdf-updater.timer
    state: started
    enabled: true
    scope: user
