---
- name: Add repository
  apt_repository:
    repo: ppa:martin-frost/thoughtbot-rcm
    state: present
  become: yes

- name: Install package
  apt:
    name: rcm
    state: present
    update_cache: yes
  become: yes
