---
- name: Create directory
  file:
    path: "{{ fisher_dir }}"
    state: directory

- name: Download file
  get_url:
    url: https://git.io/fisher
    dest: "{{ fisher_dir }}/fisher.fish"

- name: Install packages
  shell: "fisher add {{ item }}"
  args:
    executable: /usr/bin/fish
  with_items: "{{ fisher_packages }}"
  when: fisher_packages is defined
