---
- name: Add repository key
  apt_key:
    id: "{{ spotify_repo_key_id }}"
    keyserver: "{{ spotify_repo_key_server }}"
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ spotify_repo }}"
    filename: spotify
  become: true

- name: Install packages
  apt:
    name: "{{ spotify_packages }}"
    state: present
  become: true
