---
- name: "Clone {{ version_manager_name }}"
  git:
    repo: "{{ version_manager_repo }}"
    dest: "{{ version_manager_dest }}"
    version: "{{ version_manager_version }}"

- name: "Clone {{ version_manager_name }} plugins"
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ item.value.dest }}"
    version: "{{ item.value.version }}"
  with_dict: "{{ version_manager_plugins }}"
  when: version_manager_plugins is defined

- name: Create systemd user directory
  file:
    path: "{{ systemd_user_dir }}"
    state: directory

- name: "Copy {{ version_manager_name }} updater timer"
  template:
    src: updater.timer.j2
    dest: "{{ systemd_user_dir }}/{{ version_manager_name }}-updater.timer"

- name: "Copy {{ version_manager_name }} updater service"
  template:
    src: updater.service.j2
    dest: "{{ systemd_user_dir }}/{{ version_manager_name }}-updater.service"

- name: "Enable {{ version_manager_name }} updater timer"
  systemd:
    name: "{{ version_manager_name }}-updater.timer"
    state: started
    enabled: yes
    daemon_reload: yes
    user: yes
