---
- name: Download binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    checksum: "{{ docker_compose_checksum }}"
  become: true

- name: Change permissions
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  become: true
