---
- name: Add repository key
  apt_key:
    id: BA309D7C0CBE9A2DF584AC50A074F0583066C9C9
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/daniruiz/flat-remix/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: flat-remix
  become: true

- name: Install packages
  apt:
    name: "{{ flat_remix_packages }}"
    state: present
  become: true
