---
- name: Add repository
  apt_repository:
    repo: ppa:daniruiz/flat-remix
    state: present
    filename: flat-remix
  become: true

- name: Install packages
  apt:
    name: "{{ flat_remix_packages }}"
    state: present
    update_cache: true
  become: true

- name: Set GTK theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'{{ flat_remix_gtk_theme }}'"
    state: present

- name: Set icon theme
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'{{ flat_remix_icon_theme }}'"
    state: present

- name: Set user theme
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'{{ flat_remix_user_theme }}'"
    state: present
