---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install dependencies
      apt:
        name: git
        state: present
        update_cache: true

  roles:
    - role: pyenv
      vars:
        pyenv_version: v1.2.8

    - role: rbenv
      vars:
        rbenv_version: v1.1.1
