---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install dependencies
      apt:
        name: [curl, git]
        update_cache: true

  vars:
    asdf_plugins:
      - name: python
        versions:
          - number: 3.7.0

      - name: ruby
        versions:
          - number: 2.5.1

  roles:
    - asdf
