---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install dependencies
      apt:
        name: git
        state: present
        update_cache: true

  roles:
    - role: pyenv
      vars:
        pyenv_version: v1.2.8
        pyenv_versions:
          - 2.7.15
          - 3.7.2


    - role: rbenv
      vars:
        rbenv_version: v1.1.1
        rbenv_versions:
          - 2.6.0
