---
- name: Install package
  apt:
    name: git
    state: present
  become: true

- name: Copy configuration file
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
  when: git_config is defined
  tags: dotfiles
