---
- name: Install git
  community.general.homebrew:
    name: git

- name: Symlink git.fish
  ansible.builtin.file:
    src: "{{ role_path }}/files/git.fish"
    dest: ~/.config/fish/conf.d/git.fish
    state: link
    force: true
  tags: dotfiles
