---
- name: Install package
  apt:
    name: git
    state: present
  become: yes

- name: Copy fish script
  file:
    src: "{{ role_path }}/files/git.fish"
    dest: ~/.config/fish/conf.d/git.fish
    state: link
