---
- name: Install package
  apt:
    name: git
    state: present
  become: true

- name: Create config directory
  file:
    path: ~/.config/git
    state: directory

- name: Generate config file
  template:
    src: config.j2
    dest: ~/.config/git/config
  when: git_config is defined
