---
- name: Install package
  apt:
    name: git
    state: present
  become: true

- name: Add fish abbreviations
  template:
    src: git.fish.j2
    dest: ~/.config/fish/conf.d/git.fish
  when: git_fish_abbrs is defined
