---
- name: Install packages
  community.general.homebrew:
    name:
      - awscli
      - fd
      - gh
      - htop
      - postgresql
      - redis
      - ripgrep
      - tree

- name: Install packages (cask)
  community.general.homebrew_cask:
    name:
      - 1password
      - authy
      - docker
      - google-chrome
      - iterm2
      - notion
      - slack
      - spotify
      - zoom
