---

- name: Tap cask-versions repositories
  community.general.homebrew_tap:
    name: homebrew/cask-versions

- name: Install packages
  community.general.homebrew:
    name:
      - awscli
      - awsebcli
      - fd
      - gh
      - ghcup
      - gpg
      - htop
      - postgresql
      - redis
      - ripgrep
      - rustup-init
      - tree

- name: Install casks packages
  community.general.homebrew_cask:
    name:
      - 1password
      - authy
      - docker
      - google-chrome
      - grammarly-desktop
      - iterm2-beta
      - ngrok
      - slack
      - spotify
      - zoom
