---
- name: Tap repositories
  community.general.homebrew_tap:
    name:
      - cormacrelf/tap # dark-notify
      - git-chglog/git-chglog
      - homebrew/cask-versions # iterm2-beta

- name: Install packages
  community.general.homebrew:
    name:
      - autojump
      - aws-vault
      - awscli
      - awsebcli
      - dark-notify
      - direnv
      - fd
      - fzf
      - gh
      - ghcup
      - git
      - git-chglog
      - gpg
      - haskell-stack
      - htop
      - luarocks
      - rcm
      - ripgrep
      - rustup-init
      - starship
      - terraform
      - tfsec
      - tmate
      - tree
      - watch

- name: Install casks packages
  community.general.homebrew_cask:
    name:
      - 1password
      - authy
      - docker
      - google-chrome
      - grammarly-desktop
      - iterm2-beta
      - ngrok
      - notion
      - rectangle
      - slack
      - spotify
      - tunnelblick
      - visual-studio-code
      - zoom
