---
- name: Tap repositories
  community.general.homebrew_tap:
    name:
      - cormacrelf/tap
      - homebrew/cask-versions

- name: Install packages
  community.general.homebrew:
    name:
      - awscli
      - awsebcli
      - dark-notify
      - fd
      - gh
      - ghcup
      - gpg
      - htop
      - luarocks
      - ripgrep
      - rustup-init
      - terraform
      - tree
      - watch

- name: Install casks packages
  community.general.homebrew_cask:
    name:
      - 1password
      - authy
      - docker
      - fig
      - google-chrome
      - grammarly-desktop
      - iterm2-beta
      - ngrok
      - notion
      - slack
      - spotify
      - tunnelblick
      - visual-studio-code
      - zoom
