---
- name: Add repository key
  apt_key:
    url: "{{ slack_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ slack_repo }}"
    filename: slack
    state: present
  become: true

- name: Install packages
  apt:
    name: "{{ slack_packages }}"
    state: present
  become: true
