---
- name: Create {{ config_files_dir }} directory
  file:
    path: "{{ config_files_dir }}"
    state: directory

- name: Find {{ config_files_dir }} files
  shell: find {{ config_files_dir }} -maxdepth 1 -type f -name '*.{{ config_files_extension }}' -exec basename {} \;
  register: files
  changed_when: false

- name: Remove {{ config_files_dir }} unmanaged files
  file:
    path: "{{ config_files_dir }}/{{ item }}"
    state: absent
  with_items: "{{ files.stdout_lines | default([]) }}"
  when: item[:-(config_files_extension | length + 1 )] not in config_files.keys()

- name: Create {{ config_files_dir }} files
  copy:
    content: "{{ item.value }}"
    dest: "{{ config_files_dir }}/{{ item.key }}.{{ config_files_extension }}"
  with_dict: "{{ config_files }}"
