---
- name: Clone repository
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.tmux

- name: Link configuration file
  file:
    src: ~/.tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link
