---
asdf_repo: https://github.com/asdf-vm/asdf.git
asdf_dir: ~/.asdf
asdf_version: v0.5.1

asdf_plugins:
  - name: nodejs
    repo: https://github.com/asdf-vm/asdf-nodejs.git
    versions:
      - 8.11.4

  - name: python
    repo: https://github.com/tuvistavie/asdf-python.git
    versions:
      - 2.7.15
      - 3.7.0

  - name: ruby
    repo: https://github.com/asdf-vm/asdf-ruby.git
    versions:
      - 2.5.1
