---
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  when: tools_packages is defined

- name: Install packages
  apt:
    name: "{{ tools_packages }}"
    state: present
  become: yes
  when: tools_packages is defined
