---
- name: Add repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ virtualbox_repo_keys }}"
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ virtualbox_repo }}"
    filename: virtualbox
    state: present
  become: true

- name: Install packages
  apt:
    name: "{{ virtualbox_packages }}"
    state: present
  become: true
