---
- name: Install package
  community.general.homebrew:
    name: tmux

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0

- name: Create configuration
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.config/tmux/tmux.conf
  tags: dotfiles

- name: Create fish configuration
  ansible.builtin.copy:
    src: tmux.fish
    dest: ~/.config/fish/conf.d/tmux.fish
  tags: dotfiles
