---
- name: Install packages
  apt:
    name: "{{ tmux_packages }}"
    state: present
  become: yes

- name: Clone plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_tpm_dir }}"
    version: "{{ tmux_tpm_version }}"
  when: tmux_plugins is defined
  tags: dotfiles

- name: Create configuration file
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
  tags: dotfiles
