---
- name: Install package
  community.general.homebrew:
    name: tmux
  tags: homebrew

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0
