---
- name: Install packages
  apt:
    name: "{{ tmux_packages }}"
    state: present
  become: yes

- name: Clone plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_tpm_dir }}"
    version: "{{ tmux_tpm_version }}"
  when: tmux_plugins is defined

- name: Create configuration file
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
  tags: dotfiles
  notify: reload config

- name: Add fish abbreviations
  template:
    src: tmux.fish.j2
    dest: ~/.config/fish/conf.d/tmux.fish
  tags: dotfiles
