---
- name: Install package
  community.general.homebrew:
    name: tmux
  tags: homebrew

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    version: v3.0.0

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory
  tags: dotfiles

- name: Create config file
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.config/tmux/tmux.conf
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.copy:
    src: tmux.fish
    dest: ~/.config/fish/conf.d/tmux.fish
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish
