---
- name: Clone repository
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    version: v1.2.7

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ pyenv_packages }}"
  become: yes
