---
- include_role:
    name: version_manager
  vars:
    version_manager_name: pyenv
    version_manager_repo: "{{ pyenv_repo }}"
    version_manager_dest: "{{ pyenv_dest }}"
    version_manager_version: "{{ pyenv_version }}"
