---
- name: Clone repository
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_dir }}"
    version: v1.2.7

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items: "{{ pyenv_packages }}"
  become: true

- name: Install versions
  command: "pyenv install {{ item }}"
  args:
    creates: "{{ pyenv_dir }}/versions/{{ item }}"
  with_items: "{{ pyenv_versions }}"
