---
- name: Clone repository
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_dir }}"
    version: v1.2.7

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items: "{{ pyenv_packages }}"
  become: true

- include_tasks: version.yml
  with_dict: "{{ pyenv_versions }}"
  loop_control:
    loop_var: version
