---
- name: Clone repository
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_dest }}"
    version: "{{ pyenv_version }}"

- name: Install dependencies
  apt:
    name: "{{ pyenv_deps }}"
    state: present
    update_cache: yes
  become: yes

- name: Clone plugins
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ pyenv_dest }}/plugins/{{ item.key }}"
    version: "{{ item.value.version }}"
  with_dict: "{{ pyenv_plugins }}"
