---
- name: Clone pyenv
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_dest }}"
    version: "{{ pyenv_version }}"

- include_role:
    name: updater
  vars:
    updater_name: pyenv
    updater_dest: "{{ pyenv_dest }}"
