---
- name: Clone repository
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_dest }}"
    version: "{{ pyenv_version }}"

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ pyenv_deps }}"
  become: yes

- name: Install versions
  command: "pyenv install {{ item }}"
  args:
    creates: "{{ pyenv_dest }}/versions/{{ item }}"
  with_items: "{{ pyenv_versions }}"

- name: Clone plugins
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ pyenv_dest }}/plugins/{{ item.key }}"
    version: "{{ item.value.version }}"
  with_dict: "{{ pyenv_plugins }}"
