---
- name: Update cache
  apt:
    update_cache: yes
  become: yes

- name: Install dependencies
  apt:
    name: git
  with_items:
    - git
    - neovim
    - silversearcher-ag
    - tmux
  become: yes
