---
- name: Install dependencies
  apt:
    name: "{{ elasticsearch_dependencies }}"
    state: present
  become: true

- name: Add repository key
  apt_key:
    url: "{{ elasticsearch_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ elasticsearch_repo }}"
    state: present
    filename: elastic
  become: true

- name: Install package
  apt:
    name: elasticsearch
    state: present
  become: true
