---
- name: Add repository key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
    state: present
  become: true

- name: Install packages
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: true

- name: Add user to group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
