---
- name: Add repository key
  apt_key:
    url: "{{ docker_repo_key }}"
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
  become: true

- name: Install packages
  apt:
    name: "{{ docker_packages }}"
    update_cache: true
  become: true

- name: Add users to group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  become: true

- name: Pull images
  docker_image:
    name: "{{ item }}"
  with_items: "{{ docker_images }}"
