---
- name: Add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable
    filename: docker
    state: present
  become: true

- name: Install packages
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present
  become: true

- name: Add user to group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
