---
- name: Add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
  become: true

- name: Install package
  apt:
    name: docker-ce
    update_cache: true
  become: true

- name: Add user to groups
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
