---
- name: Add repository key
  apt_key:
    url: "{{ docker_repo_key }}"
  become: yes

- name: Add repository
  apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
  become: yes

- name: Install package
  apt:
    name: "{{ docker_package }}"
    update_cache: yes
  become: yes

- name: Add user to groups
  user:
    name: "{{ ansible_user_id }}"
    groups: "{{ docker_groups }}"
    append: yes
  become: yes
