---
- name: Add repository key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker
  become: true

- name: Install package
  apt:
    name: docker-ce
    state: present
    update_cache: true
  become: true

- name: Add user to group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
