---
- community.general.homebrew:
    name: starship

- ansible.builtin.copy:
    src: starship.fish
    dest: ~/.config/fish/conf.d/starship.fish

- ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
