---
- name: Install package
  community.general.homebrew:
    name: starship
  tags: homebrew

- name: Create config file
  ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.copy:
    src: starship.fish
    dest: ~/.config/fish/conf.d/starship.fish
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish
