---
- name: Install starship
  community.general.homebrew:
    name: starship

- name: Symlink starship.fish
  ansible.builtin.copy:
    src: "{{ role_path }}/files/starship.fish"
    dest: ~/.config/fish/conf.d/starship.fish
  tags: dotfiles

- name: Symlink starship.toml
  ansible.builtin.copy:
    src: "{{ role_path }}/files/starship.toml"
    dest: ~/.config/starship.toml
  tags: dotfiles
