---
- name: Install package
  community.general.homebrew:
    name: starship

- name: Create configuration
  ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
  tags: dotfiles
