---
- name: Download tarball
  get_url:
    url: "https://github.com/starship/starship/releases/download/{{ starship_version }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: /tmp

- name: Create extraction directory
  file:
    path: /tmp/starship
    state: directory

- name: Extract tarball
  unarchive:
    src: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp/starship

- name: Copy binary
  copy:
    src: /tmp/starship/starship
    dest: ~/.local/bin/
    mode: "0755"
