---
- name: Install package
  community.general.homebrew:
    name: starship
  tags: homebrew

- name: Create config file
  ansible.builtin.copy:
    src: starship.toml
    dest: ~/.config/starship.toml
  tags: dotfiles

- name: Check fish directory
  ansible.builtin.stat:
    path: ~/.config/fish/conf.d
  register: fish_conf_dir
  tags:
    - dotfiles
    - fish

- name: Copy fish config
  ansible.builtin.copy:
    src: starship.fish
    dest: ~/.config/fish/conf.d/starship.fish
  when:
    - ansible_user_shell == "/usr/local/bin/fish"
    - fish_conf_dir.stat.exists
  tags:
    - dotfiles
    - fish
