---
- community.general.homebrew:
    name: starship

- ansible.builtin.file:
    src: "{{ role_path }}/files/starship.fish"
    dest: ~/.config/fish/conf.d/starship.fish
    state: link
    force: true
  tags: dotfiles

- ansible.builtin.file:
    src: "{{ role_path }}/files/starship.toml"
    dest: ~/.config/starship.toml
    state: link
    force: true
  tags: dotfiles
