---
- name: Set params for vim
  set_fact:
    vim_params: "{{ _vim_params.vim }}"
  when: not vim_has_nvim

- name: Set params for nvim
  set_fact:
    vim_params: "{{ _vim_params.nvim }}"
  when: vim_has_nvim

- name: Install package
  apt:
    name: "{{ vim_params.package }}"
    state: present
  become: true

- import_tasks: config.yml
  tags: dotfiles

- import_tasks: ftplugin.yml
  when: vim_ftplugin_files is defined
  tags: dotfiles

- import_tasks: plugin.yml
  when: vim_plugin_files is defined
  tags: dotfiles
