---
- name: Install package
  apt:
    name: vim
    state: present
  become: true

- name: Create autoload directory
  file:
    path: "{{ vim_autoload_dir }}"
    state: directory

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_dir }}/autoload/plug.vim"

- name: Create plugin.vim file
  template:
    src: plugins.vim.j2
    dest: "{{ vim_dir }}/plugins.vim"
  notify:
    - clean_plugins
    - install_plugins

- name: Create vimrc file
  template:
    src: vimrc.j2
    dest: "{{ vim_dir }}/vimrc"

- import_role:
    name: config-files
  vars:
    config_files: "{{ vim_plugin_files }}"
    config_files_dir: "{{ vim_plugin_dir  }}"
    config_files_extension: vim
