---
pyenv_repo: https://github.com/pyenv/pyenv.git
pyenv_dest: ~/.pyenv
pyenv_version: v1.2.6

pyenv_deps:
  - build-essential
  - curl
  - libbz2-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev

pyenv_versions:
  - 2.7.15
  - 3.7.0

pyenv_plugins:
  pyenv-virtualenv:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    version: v1.1.3
