---
pyenv_dir: ~/.pyenv

pyenv_packages:
  - build-essential
  - curl
  - libbz2-dev
  - libffi-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev

pyenv_versions: []
