---
pyenv_repo: https://github.com/pyenv/pyenv.git
pyenv_dest: "{{ ansible_user_dir }}/.pyenv"
pyenv_version: v1.2.4

pyenv_deps:
  - build-essential
  - curl
  - libbz2-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev
