---
pyenv_repo: https://github.com/pyenv/pyenv.git
pyenv_dir: ~/.pyenv
pyenv_version: v1.2.7

pyenv_packages:
  - build-essential
  - curl
  - libbz2-dev
  - libffi-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev

pyenv_plugins:
  pyenv-doctor: https://github.com/pyenv/pyenv-doctor.git
