---
- name: Copy auto-updater timer
  copy:
    src: rbenv-updater.timer
    dest: ~/.config/systemd/user/rbenv-updater.timer
  notify:
    - Reload services

- name: Copy auto-updater service
  template:
    src: rbenv-updater.service.j2
    dest: ~/.config/systemd/user/rbenv-updater.service
  notify:
    - Reload services

- name: Enable auto-updater timer
  systemd:
    name: rbenv-updater.timer
    state: started
    enabled: true
    scope: user
