---
- name: Clone repository
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_dir }}"
    version: "{{ rbenv_version }}"

- include_tasks: plugin.yml
  with_items: "{{ rbenv_plugins }}"
  loop_control:
    loop_var: plugin

- name: Install versions
  command: "{{ rbenv_dir }}/bin/rbenv install {{ item }}"
  args:
    creates: "{{ rbenv_dir }}/versions/{{ item }}"
  with_items: "{{ rbenv_versions }}"
  when: rbenv_versions is defined
