---
- name: Install package
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: yes

- name: Create user
  postgresql_user:
    name: "{{ postgres_user }}"
    role_attr_flags: "{{ postgres_roles | join(',') }}"
  become: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
    state: present
  become: yes
  become_user: postgres
