---
- hosts: localhost
  roles:
    - role: asdf
      tags: asdf
    - role: fish
      tags: fish
    - role: git
      tags: git
    - role: github
      tags: git
    - role: starship
    - role: oh-my-tmux
      tags: tmux
    - role: ripgrep
      tags: ripgrep
