---
- name: Create directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Copy service unit
  copy:
    src: ssh-agent.service
    dest: ~/.config/systemd/user/ssh-agent.service

- name: Enable/Start service
  systemd:
    name: ssh-agent
    state: started
    enabled: yes
    daemon_reload: yes
    user: yes
