---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/nvim
    - ~/.local/share/nvim/site/autoload

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Create plugins file
  template:
    src: plugins.vim.j2
    dest: ~/.config/nvim/plugins.vim
  notify: install plugins

- name: Create init file
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim
