# vi: ft=yaml.ansible
---
- name: Install package
  community.general.homebrew:
    name: neovim
  tags: homebrew

- name: Install package manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Define neovim_plugins
  ansible.builtin.set_fact:
    neovim_plugins: "{{ neovim_default_plugins | combine(neovim_extra_plugins) }}"
  tags: dotfiles

- name: Create plugins.lua
  ansible.builtin.template:
    src: init.lua.j2
    dest: ~/.config/nvim/init.lua
    mode: 400
  tags: dotfiles

- name: Create plugins.lua
  ansible.builtin.template:
    src: plugins.lua.j2
    dest: ~/.config/nvim/lua/plugins.lua
    mode: 400
  tags: dotfiles
