---
- name: Install package
  community.general.homebrew:
    name:
      - neovim
      # language servers
      - bash-language-server
      - lua-language-server
      - rust-analyzer
      - terraform-ls
  tags: homebrew

- name: Install Docker language server
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
  loop:
    - { name: "@ansible/ansible-language-server", version: 0.7.2 }
    - { name: "dockerfile-language-server-nodejs", version: 0.9.0 }
    - { name: "yaml-language-server", version: 1.8.0 }

- name: Create docker-langserver wrapper
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "~/.local/bin/{{ item }}"
    mode: "0755"
  loop:
    - ansible-language-server
    - bash-language-server
    - docker-langserver
    - yaml-language-server
