---
- name: Install package
  community.general.homebrew:
    name:
      - lua-language-server
      - neovim
      - rust-analyzer
      - terraform-ls
      - yaml-language-server
  tags: homebrew

- name: Install Docker language server
  community.general.npm:
    name: dockerfile-language-server-nodejs
    version: 0.9.0
    global: true
  environment:
    PATH: "{{ asdf_nodejs_dir }}/bin:{{ ansible_env.PATH }}"

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    version: 00ec5adef58c5ff9a07f11f45903b9dbbaa1b422
    depth: 1

- name: Symlink config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: ~/.config/nvim
    state: link
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.file:
    src: "{{ role_path }}/files/neovim.fish"
    dest: ~/.config/fish/conf.d/neovim.fish
    state: link
    force: true
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish

- name: Create docker-langserver wrapper
  ansible.builtin.template:
    src: docker-langserver.j2
    dest: ~/.local/bin/docker-langserver
    mode: '0755'
