---
- name: Install package
  community.general.homebrew:
    name:
      - neovim
      # language servers
      - lua-language-server
      - rust-analyzer
      - terraform-ls
      - yaml-language-server
  tags: homebrew

- name: Install Docker language server
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
  environment:
    PATH: "{{ asdf_nodejs_dir }}/bin:{{ ansible_env.PATH }}"
  loop:
    - { name: bash-language-server, version: 3.0.4 }
    - { name: dockerfile-language-server-nodejs, version: 0.9.0 }

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    version: 00ec5adef58c5ff9a07f11f45903b9dbbaa1b422
    depth: 1

- name: Symlink config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: ~/.config/nvim
    state: link
  tags: dotfiles

- name: Copy fish config
  ansible.builtin.file:
    src: "{{ role_path }}/files/neovim.fish"
    dest: ~/.config/fish/conf.d/neovim.fish
    state: link
    force: true
  when: ansible_user_shell == "/usr/local/bin/fish"
  tags:
    - dotfiles
    - fish

- name: Create docker-langserver wrapper
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "~/.local/bin/{{ item }}"
    mode: "0755"
  loop:
    - bash-language-server
    - docker-langserver
