---
- name: Install packages
  apt:
    name: "{{ neovim_packages }}"
    state: present
  become: yes

- import_tasks: providers.yml

- name: Create autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Create configuration directory
  file:
    path: ~/.config/nvim
    state: directory

- name: Create configuration file
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim
  notify: "install plugins"
