---
- name: Install package
  pacman:
    name: neovim
  become: yes

- name: Install Node.js provider
  npm:
    name: neovim
    executable: "{{ item }}"
    global: yes
  with_items: "{{ neovim_nodejs_executables }}"

- name: Install Python provider
  pip:
    name: neovim
    executable: "{{ item }}"
  with_items: "{{ neovim_python_executables }}"

- name: Install Ruby provider
  gem:
    name: neovim
    executable: "{{ item }}"
  with_items: "{{ neovim_ruby_executables }}"
