---
- name: Install packages
  apt:
    name: "{{ neovim_packages }}"
    state: present
  become: true

- import_tasks: providers.yml

- name: Create autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/nvim
    - ~/.config/nvim/autoload
  tags: dotfiles

- name: Create files
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/nvim/{{ item }}"
  with_items:
    - init.vim
    - autoload/has.vim
  tags: dotfiles
