---
- name: Install packages
  apt:
    name: neovim
    state: present
  become: yes

- name: Install python2 provider
  pip:
    name: pynvim
    executable: "{{ neovim_providers.python2 | dirname }}/pip"
    state: present
  when: neovim_providers.python2 is defined

- name: Install python3 provider
  pip:
    name: pynvim
    executable: "{{ neovim_providers.python3 | dirname }}/pip"
    state: present
  when: neovim_providers.python3 is defined

- name: Install ruby provider
  gem:
    name: neovim
    executable: "{{ neovim_providers.ruby | dirname }}/gem"
    state: present
    build_flags:
      - "--bindir {{ neovim_providers.ruby | dirname }}"
  when: neovim_providers.ruby is defined

- name: Create autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Create configuration directory
  file:
    path: ~/.config/nvim
    state: directory

- name: Create configuration file
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim
  notify: "install plugins"
