---
- name: Install neovim
  community.general.homebrew:
    name: neovim

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Create init.lua file
  ansible.builtin.copy:
    src: init.lua
    dest: ~/.config/nvim/init.lua

- name: Create lua directory
  ansible.builtin.file:
    path: ~/.config/nvim/lua
    state: directory

- name: Create lua/plugins.lua file
  ansible.builtin.copy:
    src: plugins.lua
    dest: ~/.config/nvim/lua/plugins.lua
