---
- name: Install packages
  apt:
    name: neovim
    state: present
  become: yes

- name: Create autoload directory
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Download plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Copy init.vim
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vim
  notify: "install plugins"

- name: Create directories
  file:
    path: "~/.config/nvim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - plugin

- name: Copy files
  template:
    src: "{{ item }}.j2"
    dest: "~/.config/nvim/{{ item }}"
  with_items:
    - autoload/has.vim
    - plugin/colorscheme.vim
    - plugin/mappings.vim
