---
- name: Install package
  community.general.homebrew:
    name: neovim

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Create config directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
  tags: dotfiles

- name: Copy config file
  ansible.builtin.copy:
    src: init.lua
    dest: ~/.config/nvim/init.lua
  tags: dotfiles

- name: Create lua directory
  ansible.builtin.file:
    path: ~/.config/nvim/lua
    state: directory
  tags: dotfiles

- name: Copy plugins.lua file
  ansible.builtin.copy:
    src: plugins.lua
    dest: ~/.config/nvim/lua/plugins.lua
  tags: dotfiles

- name: Check fish directory
  ansible.builtin.stat:
    path: ~/.config/fish/conf.d
  register: fish_conf_dir
  tags:
    - dotfiles
    - fish

- name: Copy fish config
  ansible.builtin.copy:
    src: neovim.fish
    dest: ~/.config/fish/conf.d/neovim.fish
  when:
    - ansible_user_shell == "/usr/local/bin/fish"
    - fish_conf_dir.stat.exists
  tags:
    - dotfiles
    - fish
