# vi: ft=yaml.ansible
---
- name: Install package
  community.general.homebrew:
    name: neovim
  tags: homebrew

- name: Install package manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Define neovim_plugins
  ansible.builtin.set_fact:
    neovim_plugins: "{{ neovim_default_plugins | combine(neovim_extra_plugins) }}"
  tags: dotfiles

- name: Create plugins.lua
  ansible.builtin.template:
    src: init.lua.j2
    dest: ~/.config/nvim/init.lua
    mode: 400
  tags: dotfiles

- name: Create lua/plugins.lua
  ansible.builtin.template:
    src: plugins.lua.j2
    dest: ~/.config/nvim/lua/plugins.lua
    mode: 400
  tags: dotfiles

- name: Create after/plugin
  ansible.builtin.file:
    path: ~/.config/nvim/after/plugin
    state: directory
  tags: dotfiles

- name: Install dependencies
  community.general.homebrew:
    name: "{{ item.value.dependencies }}"
  when: item.value.dependencies is defined
  with_dict: "{{ neovim_lspconfig_servers }}"
  tags: homebrew

- name: Create after/plugin/lspconfig.lua
  ansible.builtin.template:
    src: lspconfig.lua.j2
    dest: ~/.config/nvim/after/plugin/lspconfig.lua
    mode: 400
  when: neovim_lspconfig_servers is defined
  tags: dotfiles
