---
- name: Install package
  community.general.homebrew:
    name:
      - neovim
      # language servers
      - ansible-language-server
      - bash-language-server
      - lua-language-server
      - rust-analyzer
      - terraform-ls
      - yaml-language-server
  tags: homebrew

- name: Install Docker language server
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
  loop:
    - { name: "dockerfile-language-server-nodejs", version: 0.9.0 }
