---
- name: Install package
  community.general.homebrew:
    name: neovim

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Symlink init.lua file
  ansible.builtin.file:
    src: "{{ role_path }}/files/init.lua"
    dest: ~/.config/nvim/init.lua
    state: link
    force: true
  tags: dotfiles

- name: Symlink lua directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/lua"
    dest: ~/.config/nvim/lua
    state: link
    force: true
  tags: dotfiles

- name: Check fish directory
  ansible.builtin.stat:
    path: ~/.config/fish/conf.d
  register: fish_conf_dir
  tags:
    - dotfiles
    - fish

- name: Copy fish config
  ansible.builtin.copy:
    src: neovim.fish
    dest: ~/.config/fish/conf.d/neovim.fish
  when:
    - ansible_user_shell == "/usr/local/bin/fish"
    - fish_conf_dir.stat.exists
  tags:
    - dotfiles
    - fish
