---
- name: Install package
  community.general.homebrew:
    name: neovim

- name: Install plugin manager
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Create configuration
  ansible.builtin.copy:
    src: init.lua
    dest: ~/.config/nvim/init.lua
  tags: dotfiles

- name: Create plugins configuration
  ansible.builtin.copy:
    src: lua/plugins.lua
    dest: ~/.config/nvim/lua/plugins.lua
  tags: dotfiles

- name: Create fish configuration
  ansible.builtin.copy:
    src: neovim.fish
    dest: ~/.config/fish/conf.d/neovim.fish
  tags: dotfiles
