---
- name: Install python2 provider
  pip:
    name: pynvim
    state: present
    executable: "{{ neovim_providers.python2 | dirname }}/pip"
  when: neovim_providers.python2 is defined

- name: Install python3 provider
  pip:
    name: pynvim
    state: present
    executable: "{{ neovim_providers.python3 | dirname }}/pip"
  when: neovim_providers.python3 is defined

- name: Install ruby provider
  gem:
    name: neovim
    executable: "{{ neovim_providers.ruby | dirname }}/gem"
    state: present
  when: neovim_providers.ruby is defined
