---
- name: Create autoload directory
  file:
    path: "{{ vim_plug_dir }}"
    state: directory

- name: Download plugin manager
  get_url:
    url: "{{ vim_plug_url }}"
    dest: "{{ vim_plug_dir }}/plug.vim"
